name: OpenAPI
slug: openapi
categories:
    - Development
description: 'The OpenAPI Specification: a broadly adopted industry standard for describing modern APIs.'
is_free: false
logo: https://raw.githubusercontent.com/apis-list/apis-list/main/apis/openapi/logo_256x256.png
type: REST
is_active: true
links:
    - name: Docs / Website
      url: https://www.openapis.org
