name: Product Hunt
slug: product-hunt
categories:
    - Commerce
    - Jobs
    - Marketing & SEO
description: The best new products, every day. Product Hunt is a curation of the best new products, every day. Discover the latest mobile apps, websites, and technology products that everyone's talking about
is_free: false
logo: https://raw.githubusercontent.com/apis-list/apis-list/main/apis/product-hunt/logo_256x256.png
type: REST
is_active: true
libraries:
    - name: Product Hunt Alfred SDK by Loris Guignard
      homepage_uri: https://github.com/loris/alfred-producthunt-workflow
      source_code_uri: ""
      platform: Python
    - name: Product Hunt Android SDK by Jasper van Riet
      homepage_uri: https://github.com/JaspervanRiet/Jager
      source_code_uri: ""
      platform: Java
    - name: Product Hunt Android SDK by Prashan Dharmasena
      homepage_uri: https://github.com/qrazhan/hunter2
      source_code_uri: ""
      platform: Java
    - name: Product Hunt NodeJS SDK by Shubham Naik
      homepage_uri: http://huntlytics.shub.club
      source_code_uri: https://github.com/4shub/huntlytics
      platform: Node.js
    - name: Product Hunt JavaScript SDK by Pusher
      homepage_uri: https://github.com/pusher-community/pusher-realtime-producthunt
      source_code_uri: ""
      platform: JavaScript
    - name: Product Hunt Swift SDK by Raul Riera
      homepage_uri: https://github.com/raulriera/HuntingKit
      source_code_uri: ""
      platform: Swift
    - name: Product Hunt Swift SDK by Tosin Afolabi
      homepage_uri: https://github.com/TosinAF/thenews
      source_code_uri: ""
      platform: Swift
    - name: Product Hunt JavaScript SDK
      homepage_uri: https://github.com/producthunt/producthunt-api
      source_code_uri: ""
      platform: JavaScript
links:
    - name: Docs / Website
      url: https://api.producthunt.com/v2/docs
